enable-whitelist: false
blacklist:
  - sosi
  - admin

whitelist:
  - test
  - fuck

network:
  url: 'jdbc:mysql://localhost:3306/test'
  username: 'root'
  password: 'admin'

tracing:
  player-quit: true
  player-login: true
  player-join: true
  player-command: true
  player-chat: true
  player-achievement: true
  player-death: false
  server-command: true
  server-remote-command: true
  server-broadcast: true

ignored-commands:
  - we
  - ban

admin-permission: discordlogger.admin
admin-discord: 'Example#9999'

bot:
  #Статус бота: true - включен, false - выключен
  enabled: true
  #Префикс бота в Discord
  prefix: '~'
  #Токен бота
  token: ''
  #ID канала для сообщений
  channel-id: ''
  #Использование команд только в указаном канале
  command-only-channel: true
  #Локал-чат
  local-chat: true
  #Время для подтверждения связки аккаунтов (в секундах)
  authentication-time: 60
  #Название сервера
  server-name: 'вашим сервером'